title: "My LeetCode Solutions"
description: "A collection of my LeetCode solutions organized by topic"
theme: jekyll-theme-cayman

collections:
  problems:
    output: true
    permalink: /problems/:title/
