name: Auto Update Index and Stats

on:
  push:
    paths:
      - "arrays/**"
      - "strings/**"
      - "**/*.cpp"
      - "**/*.c"
      - "**/*.py"
      - "**/*.java"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate stats
        run: |
          mkdir -p _data
          total=$(find arrays strings -type f | wc -l)
          langs=$(find arrays strings -type f | sed -n 's/.*\.//p' | sort -u | tr '\n' ',' | sed 's/,$//')
          updated=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

          cat > _data/leetcode_stats.yml <<EOL
total: $total
languages: [${langs}]
last_updated: "$updated"
EOL

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add _data/leetcode_stats.yml
          git commit -m "Update stats" || echo "No changes to commit"
          git push
