name: Auto Update Index and Stats

on:
  push:
    branches:
      - main            # change to "master" if that's your default
    paths:
      - "**"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate stats
        shell: bash
        run: |
          set -e
          mkdir -p _data

          # find files (ignore missing dirs)
          files=$(find arrays strings -type f 2>/dev/null || true)
          total=$(echo "$files" | wc -l | xargs)

          # collect unique extensions
          langs=$(echo "$files" | awk -F. 'NF>1{print $NF}' | sort -u | tr '\n' ',' | sed 's/,$//')
          updated=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

          # write YAML (note the indentation so it's part of the run block!)
          cat > _data/leetcode_stats.yml <<EOL
          total: $total
          languages: [${langs}]
          last_updated: "$updated"
          EOL

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add _data/leetcode_stats.yml
          git pull
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Update stats"
          git push
